spring:
  application:
    name: spring-boot-opensearch
  jackson:
    serialization:
      INDENT_OUTPUT: true

opensearch:
  uris: http://localhost:9200
  username: admin
  password: admin

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
